version: '3.8'

services:
  ros2-drone-fleet:
    build: .
    container_name: drone_fleet_backend
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
    volumes:
      - ./src:/workspace/src
      - ./config:/workspace/config
      - ./launch:/workspace/launch
      - ./worlds:/workspace/worlds
      - ./models:/workspace/models
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/humble/setup.bash && bash"